### ISSUE TITLE
XDebug not available

### ISSUE THREAD

**Issue by Stefan39** [nfrastack/container-nginx-php-fpm#66]
Hi Dave,

on my .env file I have enabled XDebug:
```
...
PHP_ENABLE_XDEBUG=TRUE
PHP_MEMORY_LIMIT=2G
PHP_XDEBUG_MODE=develop
PHP_XDEBUG_CLIENT_HOST=host.docker.internal
PHP_XDEBUG_CLIENT_PORT=9003
```

my docker-compose.yml:
```
services:

  php:
    build: ./docker
    container_name: "${PROJECT_NAME}-app"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.${DOMAIN_SUFFIX}`)"
    env_file:
      - ./.env
    ports:
      - "9003:9003"
    volumes:
      # Source code
      - ./app:/www/html
    networks:
      frivol:
      web:
        aliases:
          - "${PROJECT_NAME}.${DOMAIN_SUFFIX}"
networks:
  frivol:
    driver: bridge
  web:
    external: true
```

but xdebug are not available on web and also on cli.

My Dockerfile:
```
FROM tiredofit/nginx-php-fpm:debian-8.2

# additional ENV vars
ENV NODE_VERSION=20.5.1
ENV NVM_DIR=/root/.nvm

# since we don't use zabbix remove it right away
ENV CONTAINER_ENABLE_MONITORING=false

# Install NVM for node
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
RUN . "$NVM_DIR/nvm.sh" \
    && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" \
    && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" \
    && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"

# Install npm and yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt update \
    && apt install vim nodejs yarn -y

RUN php-ext enable redis \
    && php-ext enable calendar \
    && php-ext enable zip
```

I have see an old issue what closed by inactivity for php-5.6. I have also try it to enable byself `&& php-ext enable xdebug` but this also not works.

Unfortunatelly i cannot test it with alpine or other image at time. Do you know what's going wrong here?
